# Generated by Django 5.1.3 on 2025-12-10 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0002_seed_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembroequipo',
            options={},
        ),
        migrations.RemoveField(
            model_name='miembroequipo',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='miembroequipo',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='miembroequipo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_miembros/'),
        ),
        migrations.AlterField(
            model_name='miembroequipo',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miembroequipo',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miembroequipo',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='ArchivoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_trabajo/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_trabajo', to='portafolio_app.miembroequipo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
