# Generated by Django 5.1.3 on 2025-12-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0003_alter_miembroequipo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivotrabajo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
