# Generated by Django 5.1.3 on 2025-12-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0004_archivotrabajo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivotrabajo',
            name='seccion',
            field=models.CharField(blank=True, default='', help_text='Sección donde clasificar el archivo', max_length=100),
        ),
    ]
