# Generated by Django 5.1.3 on 2025-12-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0005_archivotrabajo_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='archivotrabajo',
            name='seccion',
            field=models.ForeignKey(help_text='Sección donde clasificar el archivo', on_delete=django.db.models.deletion.CASCADE, to='portafolio_app.seccion'),
        ),
    ]
